CAMERA_RTSP_URL="rtsp://USER:PASS@192.168.1.68:554/live/ch00_0"
YOUTUBE_RTMP_URL="rtmps://a.rtmp.youtube.com/live2/xxxx-xxxx-xxxx"

FFMPEG_BIN="ffmpeg"
FFMPEG_LOGLEVEL="warning"
RTSP_TRANSPORT="tcp"

AI_ENABLED="1"
AI_WIDTH="640"
AI_HEIGHT="360"
AI_FPS="2"
AI_MOTION_THRESHOLD="25"
AI_MIN_AREA="1500"
AI_EVENT_COOLDOWN="10"
AI_SNAPSHOT_DIR="$HOME/.note9-hub/snapshots"
AI_TFLITE_MODEL=""
AI_LABELS=""
AI_CLASSES="person,car,truck,bus,motorcycle,bicycle"
AI_SCORE_THRESHOLD="0.40"
