#!/bin/sh
#
# Start logging
#

ft_mode=`cat /tmp/ft_mode`

if [ "$ft_mode" == "4" ];then
	/etc/init.d/S10mdev start
	if [ -d /mnt/media/mmcblk0p1 ]; then
	  mmcdir="/mnt/media/mmcblk0p1"
	elif [ -d /mnt/media/mmcblk0 ]; then
	  mmcdir="/mnt/media/mmcblk0"
	fi
	mtbf_log_dir=$mmcdir/log/MTBF	
	if [ ! -d $mtbf_log_dir ]; then
		mkdir -p $mtbf_log_dir
	fi
fi

start() {
	printf "Starting logging: "
	if [ "$ft_mode" == "4" ];then
		start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /sbin/syslogd -- -n -b 99 -s 2097151 -S -O $mtbf_log_dir/MTBF_log
	  #start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /tmp/busybox syslogd -- -n -b 99 -s 2097151 -S -O $mtbf_log_dir/MTBF_log
	else
		 start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /sbin/syslogd -- -n -b 10 -S
		#start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /tmp/busybox syslogd -- -n -b 10 -S
	fi
	start-stop-daemon -b -S -q -m -p /var/run/klogd.pid --exec /sbin/klogd -- -n
	#start-stop-daemon -b -S -q -m -p /var/run/klogd.pid --exec /tmp/busybox klogd -- -n
	echo "OK"
}

stop() {
	printf "Stopping logging: "
	start-stop-daemon -K -q -p /var/run/syslogd.pid
	start-stop-daemon -K -q -p /var/run/klogd.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
