name: Build MiiCam RTSPD
on: 
  workflow_dispatch: # Cho phép bấm nút chạy thủ công trên Web GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Tự build môi trường từ Dockerfile của Repo
        run: |
          # Server GitHub sẽ tự cài trình biên dịch từ Dockerfile của bạn
          docker build -t my-miicam-env .

      - name: Biên dịch file Binary RTSPD
        run: |
          # Chạy lệnh make bên trong môi trường vừa tự build
          docker run -i -v "${{ github.workspace }}:/workspace" -w /workspace my-miicam-env /bin/bash -c 'make rtspd'

      - name: Tải file Binary rtspd về máy
        uses: actions/upload-artifact@v4
        with:
          name: rtspd-camera-binary
          path: tools/bin/rtspd2MP # Kiểm tra thư mục này sau khi workflow chạy xong
